### ISSUE TITLE
mtu.yml is failing with updated files

### ISSUE THREAD

**Issue by mfriyas** [Azure/sonic-mgmt#1021]
While executing mtu.yml the script is failing.

Configured jumbo frames mtu (9216) on fanout, leaf and server ports. Some packets not received properly at ptf end.

root@c47170c83c2d:~# ptf --test-dir ptftests mtu_test.MtuTest   --platform-dir ptftests  --platform remote  -t "testbed_type='t1';router_mac='20:04:0f:3e:ff:49';testbed_mtu=9000"  --relax --debug info --log-file /tmp/mtu_test.MtuTest.2019-07-19-09:25:29.log --socket-recv-size 16384 2>&1
WARNING: No route found for IPv6 destination :: (no default route?)
mtu_test.MtuTest ... FAIL

======================================================================
FAIL: mtu_test.MtuTest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ptftests/mtu_test.py", line 151, in runTest
    self.check_icmp_mtu()
  File "ptftests/mtu_test.py", line 90, in check_icmp_mtu
    (matched_index, received) = verify_packet_any_port(self, masked_exp_pkt, dst_port_list)
  File "/usr/lib/python2.7/dist-packages/ptf/testutils.py", line 2373, in verify_packet_any_port
    % (ports, device_number, result.format()))
AssertionError: Did not receive expected packet on any of ports [0, 1] for device 0.
========== EXPECTED ==========
Mask: ???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
========== RECEIVED ==========
54 total packets. Displaying most recent 3 packets:
------------------------------
0000   52 54 00 0D 80 34 20 04  0F 3E FF 49 86 DD 6C 07   RT...4 ..>.I..l.
0010   C7 C0 00 20 06 01 FC 00  00 00 00 00 00 00 00 00   ... ............
0020   00 00 00 00 00 25 FC 00  00 00 00 00 00 00 00 00   .....%..........
0030   00 00 00 00 00 26 9F 2C  00 B3 0A C2 3E 0C 6A 7A   .....&.,....>.jz
0040   29 47 80 10 06 88 39 08  00 00 01 01 08 0A 02 A7   )G....9.........
0050   84 D9 12 0E 28 E3                                  ....(.
------------------------------
0000   52 54 00 EB E9 B0 20 04  0F 3E FF 49 86 DD 6C 0E   RT.... ..>.I..l.
0010   A8 9D 00 20 06 01 FC 00  00 00 00 00 00 00 00 00   ... ............
0020   00 00 00 00 00 1D FC 00  00 00 00 00 00 00 00 00   ................
0030   00 00 00 00 00 1E C6 18  00 B3 40 E2 95 B4 43 45   ..........@...CE
0040   6F 53 80 10 06 68 71 43  00 00 01 01 08 0A 02 A7   oS...hqC........
0050   84 E6 12 0E 1D 3F                                  .....?
------------------------------
0000   52 54 00 B2 CF E4 20 04  0F 3E FF 49 86 DD 6C 03   RT.... ..>.I..l.
0010   6D 9D 00 20 06 01 FC 00  00 00 00 00 00 00 00 00   m.. ............
0020   00 00 00 00 00 79 FC 00  00 00 00 00 00 00 00 00   .....y..........
0030   00 00 00 00 00 7A BA BE  00 B3 A7 02 B2 B1 A6 95   .....z..........
0040   4F C0 80 10 00 DD 7D B6  00 00 01 01 08 0A 02 A7   O.....}.........
0050   84 E9 14 A7 57 82                                  ....W.
==============================

----------------------------------------------------------------------
Ran 1 test in 1.038s

FAILED (failures=1)

******************************************
ATTENTION: SOME TESTS DID NOT PASS!!!

**Comment by stcheng** [comment]
could you format your issue for better readability?
