### ISSUE TITLE
Docker shell module failed in the latest sonic-mgmt for some tasks

### ISSUE THREAD

**Issue by msosyak** [Azure/sonic-mgmt#1268]
**Description**
According to https://github.com/Azure/sonic-mgmt/issues/1243, the fix https://github.com/Azure/sonic-mgmt/pull/1253 was merged.
But this fix turned out to be incomplete and cause an error similar to previous when running some tasks with docker shell e.g. copy, template.

Here are the logs:
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 111, in run
    item_results = self._run_loop(items)
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 371, in _run_loop
    res = self._execute(variables=task_vars)
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 664, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/copy.py", line 590, in run
    self._remove_tmp_path(self._connection._shell.tmpdir)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 398, in _remove_tmp_path
    cmd = self._connection._shell.remove(tmp_path, recurse=True)
  File "/var/user/jenkins/bfn-sonic-mgmt/ansible/shell_plugins/docker.py", line 44, in remove
    argv = self.get_option('ansible_python_interpreter').split()
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 60, in get_option
    raise KeyError(to_native(e))
KeyError: 'Requested entry (plugin_type: shell plugin: docker setting: ansible_python_interpreter ) was not defined in configuration.'

fatal: [cab18-2-dut]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```

**Steps to reproduce the issue:**
1. run ecn_wred CT

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:

    ```
    (paste your output here)
    ```

**Comment by msosyak** [comment]
Here is the fix for this issue: https://github.com/Azure/sonic-mgmt/pull/1262
But it not looks like the best option which we can choose.
As I mentioned here https://github.com/Azure/sonic-mgmt/pull/1253#discussion_r353481417
"maybe it is the time to look to the docker connection plugin."
So I've spent some time and created  https://github.com/Azure/sonic-mgmt/pull/1269  where I tried to use the docker connection plugin.

@qiluo-msft @lguohan Please have a look to https://github.com/Azure/sonic-mgmt/pull/1269
