### ISSUE TITLE
ERROR! Invalid vault password was provided from file (/var/sonic/.password)

### ISSUE THREAD

**Issue by gord1306** [Azure/sonic-mgmt#1289]
**Description**
I am trying to use the latest sonic-mgmt (update to ansible 2.8.7) to perform ansible testing. In the previous version, I can specify an empty file as the vault password file e.g. `./testbed-cli.sh add-topo 2-2_t0 ~/.password -e ptf_imagetag=201910`

But for the latest version, it will report the error messages
```
sonic@5bc080718e5b:~/sonic-mgmt/ansible$ ./testbed-cli.sh add-topo 2-2_t0 ~/.password -e ptf_imagetag=201911
Deploying topology '2-2_t0'
reading
Found topology 2-2_t0
[WARNING]: Error in vault password file loading (default): Invalid vault password was provided from file (/var/sonic/.password)

ERROR! Invalid vault password was provided from file (/var/sonic/.password)
```

**Describe the results you received:**
```
ERROR! Invalid vault password was provided from file (/var/sonic/.password)
```

**Describe the results you expected:**
Success to add topology without the vault error

Is anyone know what I miss to setup. Thanks

**Comment by lguohan** [comment]
you can put any string in the password.txt file.  it looks like the ANSIble 2.8.7 do not accept empty password file for vault

**Comment by gord1306** [comment]
Thanks @lguohan, the vault fille issue can pass. And there is a new issue. It looks like miss python module shlex in the sonic-mgmt. I tried to pip install ushlex but still can not fix it. Did you see this issue before?

```
TASK [Read dut minigraph] ***************************************************************************************************************************************
task path: /var/sonic/sonic-mgmt/ansible/testbed_add_vm_topology.yml:70
Tuesday 17 December 2019  07:21:03 +0000 (0:00:00.091)       0:00:00.501 ******
Using module file /var/sonic/sonic-mgmt/ansible/library/conn_graph_facts.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: sonic
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 114, in <module>
  File "<stdin>", line 106, in _ansiballz_main
  File "<stdin>", line 45, in invoke_module
  File "/tmp/ansible_conn_graph_facts_payload_LrJNDY/ansible_conn_graph_facts_payload.zip/ansible/module_utils/basic.py", line 171, in <module>
ImportError: cannot import name shlex_quote

fatal: [STR-ACS-SERV-02-2 -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 114, in <module>\n  File \"<stdin>\", line 106, in _ansiballz_main\n  File \"<stdin>\", line 45, in invoke_module\n  File \"/tmp/ansible_conn_graph_facts_payload_LrJNDY/ansible_conn_graph_facts_payload.zip/ansible/module_utils/basic.py\", line 171, in <module>\nImportError: cannot import name shlex_quote\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
[STR-ACS-SERV-02-2] TASK: Read dut minigraph (debug)>
[STR-ACS-SERV-02-2] TASK: Read dut minigraph (debug)>
```

**Comment by gord1306** [comment]
I manully comment this line in `/usr/local/lib/python2.7/dist-packages/ansible/module_utils/urls.py` , the add topo can continue

```
#import ansible.module_utils.six.moves.http_cookiejar as cookiejar
```
