### ISSUE TITLE
Loganalyzer parsing time stamp of log msg may fail with "day is out of range for month"

### ISSUE THREAD

**Issue by wangxin** [Azure/sonic-mgmt#1414]
**Description**

Loganalyzer failed with parsing time stamp from log message. This issue only happens on Feb 29.

```
TASK [test : Extract all syslog entries since the latest start marker] ********* 
task path: /root/mars/workspace/sonic-mgmt/ansible/roles/test/files/tools/loganalyzer/loganalyzer_analyze.yml:112 
Saturday 29 February 2020  13:57:14 +0000 (0:00:00.529)       0:05:54.311 ***** 
Using module file /root/mars/workspace/sonic-mgmt/ansible/library/extract_log.py 
Pipelining is enabled. 
<arc-switch1029> ESTABLISH SSH CONNECTION FOR USER: admin 
<arc-switch1029> SSH: EXEC sshpass -d12 ssh -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o 'User="admin"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/570420b13d arc-switch1029 '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=nlpfszcyvogoxksvoweryblomqfhhqls] password:" -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-nlpfszcyvogoxksvoweryblomqfhhqls ; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"'' 
Escalation succeeded 

<arc-switch1029> (1, '\n{"msg": "Error: (<type \'exceptions.ValueError\'>, ValueError(\'unconverted data remains: .324429\',), <traceback object at 0x7f8987062290>)", "failed": true, "exception": "WARNING: The below traceback may *not* be related to the actual failure.\\n  File \\"/tmp/ansible_extract_log_payload_MPeleV/__main__.py\\", line 243, in main\\n    extract_log(p[\'directory\'], p[\'file_prefix\'], p[\'start_string\'], p[\'target_filename\'])\\n  File \\"/tmp/ansible_extract_log_payload_MPeleV/__main__.py\\", line 226, in extract_log\\n    file_with_latest_line, latest_line = extract_latest_line_with_string(directory, filenames, target_string)\\n  File \\"/tmp/ansible_extract_log_payload_MPeleV/__main__.py\\", line 192, in extract_latest_line_with_string\\n    if comparator(line, target) > 0:\\n  File \\"/tmp/ansible_extract_log_payload_MPeleV/__main__.py\\", line 137, in comparator\\n    dl = convert_date(l[1])\\n  File \\"/tmp/ansible_extract_log_payload_MPeleV/__main__.py\\", line 123, in convert_date\\n    dt = datetime.datetime.strptime(str_date, \'%b %d %X\')\\n  File \\"/usr/lib/python2.7/_strptime.py\\", line 335, in _strptime\\n    data_string[found.end():])\\n", "invocation": {"module_args": {"start_string": "start-LogAnalyzer-ECN_Range_Check.2020-02-29-13:57:00", "directory": "/var/log", "target_filename": "/tmp/syslog", "file_prefix": "syslog"}}}\n', '') 
<arc-switch1029> Failed to connect to the host via ssh: 
The full traceback is: 
WARNING: The below traceback may *not* be related to the actual failure. 
  File "/tmp/ansible_extract_log_payload_MPeleV/__main__.py", line 243, in main 
    extract_log(p['directory'], p['file_prefix'], p['start_string'], p['target_filename']) 
  File "/tmp/ansible_extract_log_payload_MPeleV/__main__.py", line 226, in extract_log 
    file_with_latest_line, latest_line = extract_latest_line_with_string(directory, filenames, target_string) 
  File "/tmp/ansible_extract_log_payload_MPeleV/__main__.py", line 192, in extract_latest_line_with_string 
    if comparator(line, target) > 0: 
  File "/tmp/ansible_extract_log_payload_MPeleV/__main__.py", line 137, in comparator 
    dl = convert_date(l[1]) 
  File "/tmp/ansible_extract_log_payload_MPeleV/__main__.py", line 123, in convert_date 
    dt = datetime.datetime.strptime(str_date, '%b %d %X') 
  File "/usr/lib/python2.7/_strptime.py", line 335, in _strptime 
    data_string[found.end():]) 
fatal: [arc-switch1029-ptf32]: FAILED! => { 
    "changed": false, 
    "invocation": { 
        "module_args": { 
            "directory": "/var/log", 
            "file_prefix": "syslog", 
            "start_string": "start-LogAnalyzer-ECN_Range_Check.2020-02-29-13:57:00", 
            "target_filename": "/tmp/syslog" 
        } 
    }, 
    "msg": "Error: (<type 'exceptions.ValueError'>, ValueError('unconverted data remains: .324429',), <traceback object at 0x7f8987062290>)" 
} 
```
The exception was raised by function convert_date in ansible/library/extract_log.py

```
def convert_date(s):
    dt = None
    re_result = re.findall(r'^\S{3}\s{1,2}\d{1,2} \d{2}:\d{2}:\d{2}\.?\d*', s)
    # Workaround for pytest-ansible
    loc = locale.getlocale()
    locale.setlocale(locale.LC_ALL, (None, None))

    if len(re_result) > 0:
        str_date = re_result[0]
        try:
            dt = datetime.datetime.strptime(str_date, '%b %d %X.%f')
        except ValueError:
            dt = datetime.datetime.strptime(str_date, '%b %d %X')
    else:
        re_result = re.findall(r'^\d{4}-\d{2}-\d{2}\.\d{2}:\d{2}:\d{2}\.\d{6}', s)
        str_date = re_result[0]
        dt = datetime.datetime.strptime(str_date, '%Y-%m-%d.%X.%f')
    locale.setlocale(locale.LC_ALL, loc)

    return dt
```

When the issue was raised, the function was processing log line:
```
Feb 29 13:57:04.324429 arc-switch1029 INFO start-LogAnalyzer-ECN_Range_Check.2020-02-29-13:57:00
```

The time stamp string extracted from this log message by regular expression is:
`str_date = 'Feb 29 13:57:04.324429'`

Converting this string to datetime will fail:

```
>>> import datetime
>>> str_date = 'Feb 29 13:57:04.324429'
>>> datetime.datetime.strptime(str_date, '%b %d %X.%f')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: day is out of range for month

>>> datetime.datetime.strptime(str_date, '%b %d %X')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: .324429
```

If the time stamp extracted from syslog message do not have year, according to this discussion https://bugs.python.org/issue26460, it should be better to use time.strptime() to parse the time stamp.

**Steps to reproduce the issue:**
1. Run any test with loganalyzer enabled on Feb 29.
2.
3.

**Describe the results you received:**
Loganalyzer failed with parsing time stamp from log message.

**Describe the results you expected:**
Loganalyzer should be able to parse time stamp properly.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by wangxin** [comment]
Resolved by https://github.com/Azure/sonic-mgmt/pull/1436
