### ISSUE TITLE
Start VM failed with "Unable to get index for interface VM0601-back: No such device"

### ISSUE THREAD

**Issue by wangxin** [Azure/sonic-mgmt#1481]
**Description**
If use the testbed-cli.sh to start-vms, the defined VM cannot be started. The error message is “Unable to get index for interface VM0601-back: No such device”.

Executed cli: `./testbed-cli.sh -n 32 start-vms server_6 vault -vvv`:

```
TASK [vm_set : Start vm VM0601] ******************************************************************************************************************************************************************************
task path: /root/xinw/sonic-mgmt/ansible/roles/vm_set/tasks/start_vm.yml:44
Tuesday 24 March 2020  10:29:27 +0000 (0:00:00.069)       0:01:00.943 ********* 
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/cloud/misc/virt.py
Pipelining is enabled.
<arc-host121> ESTABLISH SSH CONNECTION FOR USER: root
<arc-host121> SSH: EXEC sshpass -d10 ssh -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o 'User="root"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/89771a2f82 arc-host121 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<arc-host121> (1, '\n{"msg": "Unable to get index for interface VM0601-back: No such device", "failed": true, "exception": "Traceback (most recent call last):\\n  File \\"/tmp/ansible_virt_payload_uT5mwF/__main__.py\\", line 593, in main\\n    rc, result = core(module)\\n  File \\"/tmp/ansible_virt_payload_uT5mwF/__main__.py\\", line 497, in core\\n    res[\'msg\'] = v.start(guest)\\n  File \\"/tmp/ansible_virt_payload_uT5mwF/__main__.py\\", line 405, in start\\n    return self.conn.create(vmid)\\n  File \\"/tmp/ansible_virt_payload_uT5mwF/__main__.py\\", line 238, in create\\n    return self.find_vm(vmid).create()\\n  File \\"/usr/lib/python2.7/dist-packages/libvirt.py\\", line 1035, in create\\n    if ret == -1: raise libvirtError (\'virDomainCreate() failed\', dom=self)\\nlibvirtError: Unable to get index for interface VM0601-back: No such device\\n", "invocation": {"module_args": {"xml": null, "name": "VM0601", "uri": "qemu:///system", "state": "running", "command": null, "autostart": null}}}\n', 'libvirt:  error : Unable to get index for interface VM0601-back: No such device\n')
<arc-host121> Failed to connect to the host via ssh: libvirt:  error : Unable to get index for interface VM0601-back: No such device
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_virt_payload_uT5mwF/__main__.py", line 593, in main
    rc, result = core(module)
  File "/tmp/ansible_virt_payload_uT5mwF/__main__.py", line 497, in core
    res['msg'] = v.start(guest)
  File "/tmp/ansible_virt_payload_uT5mwF/__main__.py", line 405, in start
    return self.conn.create(vmid)
  File "/tmp/ansible_virt_payload_uT5mwF/__main__.py", line 238, in create
    return self.find_vm(vmid).create()
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 1035, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirtError: Unable to get index for interface VM0601-back: No such device

fatal: [ARC-HOST121]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "autostart": null, 
            "command": null, 
            "name": "VM0601", 
            "state": "running", 
            "uri": "qemu:///system", 
            "xml": null
        }
    }, 
    "msg": "Unable to get index for interface VM0601-back: No such device"
}
```

The issue may be related with below interface defined in arista.xml.j2:
```
    <interface type='ethernet'>
      <model type='virtio'/>
      <target dev='{{ backplane_tap }}'/>
    </interface>
```
This change was introduced in PR https://github.com/Azure/sonic-mgmt/pull/1233

Manually check the defined VM and try to start it:
```
root@server:~# virsh list --all
 Id    Name                           State
----------------------------------------------------
 -     VM0601                         shut off

root@server:~# virsh dumpxml VM0601
<domain type='kvm'>
  <name>VM0601</name>
  <uuid>e506441b-341e-41ff-8ffc-4b1beacda67b</uuid>
  <memory unit='KiB'>2097152</memory>
  <currentMemory unit='KiB'>2097152</currentMemory>
  <vcpu placement='static'>1</vcpu>
  <resource>
    <partition>/machine</partition>
  </resource>
  <os>
    <type arch='x86_64' machine='pc-i440fx-1.5'>hvm</type>
    <boot dev='cdrom'/>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
  </features>
  <clock offset='utc'/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>restart</on_crash>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='vmdk' cache='writeback'/>
      <source file='/images/veos-vm/disks/VM0601_hdd.vmdk'/>
      <target dev='hda' bus='ide'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <source file='/images/veos-vm/images/Aboot-veos-serial-8.0.0.iso'/>
      <target dev='hdc' bus='ide'/>
      <readonly/>
      <address type='drive' controller='0' bus='1' target='0' unit='0'/>
    </disk>
    <controller type='usb' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pci-root'/>
    <controller type='ide' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x1'/>
    </controller>
    <interface type='bridge'>
      <mac address='52:54:00:bb:d6:09'/>
      <source bridge='br0'/>
      <target dev='VM0601-m'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </interface>
    <interface type='bridge'>
      <mac address='52:54:00:98:bf:97'/>
      <source bridge='br-VM0601-0'/>
      <virtualport type='openvswitch'>
        <parameters interfaceid='b096ac79-1c52-466c-affe-2090250ec4ee'/>
      </virtualport>
      <target dev='VM0601-t0'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>
    <interface type='bridge'>
      <mac address='52:54:00:90:ae:9a'/>
      <source bridge='br-VM0601-1'/>
      <virtualport type='openvswitch'>
        <parameters interfaceid='08bf26fe-2948-4339-b768-ddd432831d62'/>
      </virtualport>
      <target dev='VM0601-t1'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </interface>
    <interface type='bridge'>
      <mac address='52:54:00:0c:2c:28'/>
      <source bridge='br-VM0601-2'/>
      <virtualport type='openvswitch'>
        <parameters interfaceid='5f81b5a4-1a1b-4329-8dd9-d533eb954faa'/>
      </virtualport>
      <target dev='VM0601-t2'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </interface>
    <interface type='bridge'>
      <mac address='52:54:00:2b:e1:40'/>
      <source bridge='br-VM0601-3'/>
      <virtualport type='openvswitch'>
        <parameters interfaceid='e6f342fc-73a7-4be1-b33c-03faeb9958a7'/>
      </virtualport>
      <target dev='VM0601-t3'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>
    </interface>
    <interface type='ethernet'>
      <mac address='52:54:00:82:7b:36'/>
      <target dev='VM0601-back'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x08' function='0x0'/>
    </interface>
    <serial type='tcp'>
      <source mode='bind' host='127.0.0.1' service='7001'/>
      <protocol type='telnet'/>
      <target port='0'/>
    </serial>
    <console type='tcp'>
      <source mode='bind' host='127.0.0.1' service='7001'/>
      <protocol type='telnet'/>
      <target type='serial' port='0'/>
    </console>
    <memballoon model='virtio'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
    </memballoon>
  </devices>
  <seclabel type='dynamic' model='apparmor' relabel='yes'/>
</domain>

root@server:~# virsh start VM0601
error: Failed to start domain VM0601
error: Unable to get index for interface VM0601-back: No such device
```

**Steps to reproduce the issue:**
1. Try to start VMs on test server by running command `./testbed-cli.sh start-vms` in sonic-mgmt.
2. 
3.

**Describe the results you received:**
The VM can be defined but failed to start.

**Describe the results you expected:**
Start all the VMs successfully.

**Additional information you deem important:**

    **Output of `show version`:**

    **Attach debug file `sudo generate_dump`:**

**Comment by li7hui** [comment]
@wangxin i have meet the same problem. 
Unable to get index for interface VM0601-back: No such device

**Comment by wangxin** [comment]
@li7hui What Ubuntu version were you using on the test server?
I ran into this issue when I was testing on a server running Ubuntu 16.04. The reason was that the tap interface required by VM was not created somehow. My server was upgraded from 14.04 to 16.04 by using "do_release_upgrade". Not sure if something was broken during upgrade.

On test server running Ubuntu 14.04, starting VMs failed because of permission issue of accessing /dev/net/tun.

On another test server running fresh installed Ubuntu 18.04, starting VMs was successful. Still I need to add below to configurations to `/etc/libvirt/qemu.conf` to workaround another issue "qemu-system-x86_64: failed to initialize KVM: Permission denied".

@lguohan It looks like this issue is related with test environment. On a test server running fresh installed Ubuntu 18.04, I didn't hit this issue. Staring VMs was successful.

**Comment by li7hui** [comment]
@wangxin, 
i had the fresh installed Ubuntu 16.04, and it had the problem which says "Start VM failed with "Unable to get index for interface VM0601-back: No such device"
when i shift to fresh installed ubuntu 18.04, and above problem has gone. 

However, i still have the problem to ping vEOS VM from the sonic-mgmt docker. i can ping the STR-ACS-SERV-01 ansible_host from sonic-mgmt docker successfully, but i can't ping the vEOS VM from sonic-mgmt docker.

**Comment by feng891005** [comment]
I have encountered the same problem. Is there a workaround?

Start VM failed with "Unable to get index for interface VM0100-back: No such device

**Comment by li7hui** [comment]
@feng891005 Using freshed installed Ubuntu 18.04 may solve this problem.

**Comment by wangxin** [comment]
@li7hui I didn't have this issue. You can check if the VMs were actually started and got IP address.
* SSH to your server.
* Check VM status using `virsh list`
* Try to connect to the VMs console using telnet, for example `telnet localhost 7001` can connect to console of the first VM. `telnet localhost 7002` can connect to the 2nd, etc.
* On VMs console, check if the VMs have proper IP and network configuration.
* Check if ansible can find proper credential for accessing the VMs.

**Comment by li7hui** [comment]
@wangxin
i added following lines into the veos, and it solved my problem.
[vms_1]
VM0100 ansible_host=172.28.55.143 ansible_ssh_user=root ansible_ssh_pass=123456
VM0101 ansible_host=172.28.55.142 ansible_ssh_user=root ansible_ssh_pass=123456
VM0102 ansible_host=172.28.55.141 ansible_ssh_user=root ansible_ssh_pass=123456

**Comment by wangxin** [comment]
I am closing this issue because it works on Ubuntu 18.04. If you run into similar problem, please upgrade your test server.
