### ISSUE TITLE
pc/test_lag_2.py failed on virtual testbed t0

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-mgmt#1622]
**Description**

**Steps to reproduce the issue:**
1. py.test $PYTEST_COMMON_OPTS --log-file ~/abc.log pc/test_lag_2.py  | tee ~/abc.txt
2.
3.

**Describe the results you received:**
```
        res = self.module(*module_args, **complex_args)[self.hostname]
        if res.is_failed and not module_ignore_errors:
>           raise RunAnsibleModuleFail("run module {} failed, errmsg {}".format(self.module_name, res))
E           RunAnsibleModuleFail: run module shell failed, errmsg {'stderr_lines': [u'WARNING: No route found for IPv6 destination :: (no default route?)', u'lag_test.LacpTimingTest ... FAIL', u'', u'======================================================================', u'FAIL: lag_test.LacpTimingTest', u'----------------------------------------------------------------------', u'Traceback (most recent call last):', u'  File "/tmp/lag_test.py", line 155, in runTest', u'    self.assertTrue(abs(current_pkt_timing - float(self.packet_timing)) < 0.1, "Bad packet timing: %.2f seconds while expected timing is %d seconds from port %s out of %d intervals" % (current_pkt_timing, self.packet_timing, self.exp_iface, self.interval_count))', u'AssertionError: Bad packet timing: 30.00 seconds while expected timing is 1 seconds from port 28 out of 3 intervals', u'', u'----------------------------------------------------------------------', u'Ran 1 test in 102.329s', u'', u'FAILED (failures=1)'], u'cmd': u"ptf --test-dir /tmp lag_test.LacpTimingTest --platform-dir /root/ptftests --platform remote -t 'packet_timing=1;interval_count=3;ether_type=34825;timeout=35;exp_iface=28' --relax --debug info", u'end': u'2020-04-29 03:36:21.275888', '_ansible_no_log': False, u'stdout': u'', u'changed': True, u'start': u'2020-04-29 03:34:37.556191', u'delta': u'0:01:43.719697', u'stderr': u'WARNING: No route found for IPv6 destination :: (no default route?)\nlag_test.LacpTimingTest ... FAIL\n\n======================================================================\nFAIL: lag_test.LacpTimingTest\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/tmp/lag_test.py", line 155, in runTest\n    self.assertTrue(abs(current_pkt_timing - float(self.packet_timing)) < 0.1, "Bad packet timing: %.2f seconds while expected timing is %d seconds from port %s out of %d intervals" % (current_pkt_timing, self.packet_timing, self.exp_iface, self.interval_count))\nAssertionError: Bad packet timing: 30.00 seconds while expected timing is 1 seconds from port 28 out of 3 intervals\n\n----------------------------------------------------------------------\nRan 1 test in 102.329s\n\nFAILED (failures=1)', u'rc': 1, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'strip_empty_ends': True, u'_raw_params': u"ptf --test-dir /tmp lag_test.LacpTimingTest --platform-dir /root/ptftests --platform remote -t 'packet_timing=1;interval_count=3;ether_type=34825;timeout=35;exp_iface=28' --relax --debug info", u'removes': None, u'argv': None, u'creates': None, u'chdir': u'/root', u'stdin_add_newline': True, u'stdin': None}}, 'stdout_lines': [], u'msg': u'non-zero return code'}
```

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```
[abc.txt](https://github.com/Azure/sonic-mgmt/files/4549699/abc.txt)
[abc.log](https://github.com/Azure/sonic-mgmt/files/4549700/abc.log)

**Comment by Blueve** [comment]
**Init investigation**
lag_test.LacpTimingTest PTF test fail

**Comment by Blueve** [comment]
I got same failure after resolve nbrhosts not found issue.
Seems like it is very similar with my another testcase dir_bcast.
I add fib fixture to force refresh route table before run dir_bcast test to solve that problem, I will try same for lag_2 test.

**Comment by lguohan** [comment]
is this fixed?

**Comment by lguohan** [comment]
seems related to #2041
