### ISSUE TITLE
bgp_bounce test is broken

### ISSUE THREAD

**Issue by vsenchyshyn** [Azure/sonic-mgmt#1651]
**Description**

**Steps to reproduce the issue:**
1. Run bgp_bounce test
2.
3.

**Describe the results you received:**
Test fails on an attempt of bgp config generation.

**bgp_conf_gen.j2** uses **deployment_id_asn_map.yml** file which was renamed to **constants.yml** while back. But when you try to use the proper filename for bgp config generation and modify other to **bgp_no_export.j2** and **bgp_plain.j2** according to the changes in constants.yml (apply the diff below):

[bgp_bounce.diff.txt](https://github.com/Azure/sonic-mgmt/files/4592496/bgp_bounce.diff.txt)

 the config generation will fail with the following error log:

```
Traceback (most recent call last):
  File "/usr/local/bin/sonic-cfggen", line 322, in <module>
    main()
  File "/usr/local/bin/sonic-cfggen", line 296, in main
    print(template.render(sort_data(data)))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/admin/bgp_no_export.j2", line 18, in top-level template code
    {% block bgp_init %}
  File "/home/admin/bgp_no_export.j2", line 39, in block "bgp_init"
    {% for (name, prefix) in LOOPBACK_INTERFACE %}
ValueError: too many values to unpack
```

**Describe the results you expected:**
The test should pass

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by alanC-Cameo** [comment]
Same fail on master July/14 commit.

**Comment by alanC-Cameo** [comment]
@vsenchyshyn got rid of the "ValueError: too many values to unpack" by removing the invalid item, which may look like "Loopback0": {} as below, in LOOPBACK_INTERFACE{} in my DUT config_db.json.

"LOOPBACK_INTERFACE": {
    **"Loopback0": {}, <- remove this**
    "Loopback0|10.1.0.32/32": {},
    "Loopback0|FC00:1::32/128": {}
},
