### ISSUE TITLE
run test_nbr_health.py failed

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-mgmt#1659]
**Description**

suddenly, run test_nbr_health.py failed.

**Steps to reproduce the issue:**
1.  py.test $PYTEST_COMMON_OPTS --log-file ~/abc.log test_nbr_health.py  | tee ~/abc.tx
2.
3.

**Describe the results you received:**

```
self = <tests.common.devices.EosHost object at 0x7f9c24d16750>, module_args = ()
complex_args = {}, module_ignore_errors = False, module_async = False
res = {'deprecations': [{'msg': u'Distribution ubuntu 16.04 on host VM0103 should us...rror', 'ansible_facts': {u'discovered_interpreter_python': u'/usr/bin/python'}}

    def _run(self, *module_args, **complex_args):
        module_ignore_errors = complex_args.pop('module_ignore_errors', False)
        module_async = complex_args.pop('module_async', False)
    
        if module_async:
            def run_module(module_args, complex_args):
                return self.module(*module_args, **complex_args)[self.hostname]
            pool = ThreadPool()
            result = pool.apply_async(run_module, (module_args, complex_args))
            return pool, result
    
        res = self.module(*module_args, **complex_args)[self.hostname]
        if res.is_failed and not module_ignore_errors:
>           raise RunAnsibleModuleFail("run module {} failed, errmsg {}".format(self.module_name, res))
E           RunAnsibleModuleFail: run module eos_facts failed, errmsg {'deprecations': [{'msg': u'Distribution ubuntu 16.04 on host VM0103 should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information', 'version': u'2.12'}], 'exception': u'Traceback (most recent call last):\n  File "<stdin>", line 114, in <module>\n  File "<stdin>", line 106, in _ansiballz_main\n  File "<stdin>", line 49, in invoke_module\n  File "/tmp/ansible_eos_facts_payload_X1RH6n/__main__.py", line 403, in <module>\n  File "/tmp/ansible_eos_facts_payload_X1RH6n/__main__.py", line 391, in main\n  File "/tmp/ansible_eos_facts_payload_X1RH6n/__main__.py", line 188, in populate\n  File "/tmp/ansible_eos_facts_payload_X1RH6n/__main__.py", line 204, in platform_facts\nAttributeError: \'module\' object has no attribute \'python_version\'\n', '_ansible_no_log': False, 'module_stderr': u'Traceback (most recent call last):\n  File "<stdin>", line 114, in <module>\n  File "<stdin>", line 106, in _ansiballz_main\n  File "<stdin>", line 49, in invoke_module\n  File "/tmp/ansible_eos_facts_payload_X1RH6n/__main__.py", line 403, in <module>\n  File "/tmp/ansible_eos_facts_payload_X1RH6n/__main__.py", line 391, in main\n  File "/tmp/ansible_eos_facts_payload_X1RH6n/__main__.py", line 188, in populate\n  File "/tmp/ansible_eos_facts_payload_X1RH6n/__main__.py", line 204, in platform_facts\nAttributeError: \'module\' object has no attribute \'python_version\'\n', 'changed': False, 'module_stdout': u'', 'rc': 1, 'msg': u'MODULE FAILURE\nSee stdout/stderr for the exact error', 'ansible_facts': {u'discovered_interpreter_python': u'/usr/bin/python'}}
```

check this build for more info.

https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-test/254/

**Describe the results you expected:**

if I add `export ANSIBLE_KEEP_REMOTE_FILES=1`, then it works.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by lguohan** [comment]
if i commented "/usr/local/lib/python2.7/dist-packages/ansible/modules/network/eos/eos_facts.py" 
```
platform_facts['python_version'] = platform.python_version()
```

it also passes
