### ISSUE TITLE
Ansible action plugin "apswitch" would also use connection plugin "ssh" when multi_passwd_ssh is enable.

### ISSUE THREAD

**Issue by chiourung** [Azure/sonic-mgmt#2387]
**Description**

multi_passwd_ssh is enable by setting in ansible/group_vars/sonic/variables
`ansible_connection: multi_passwd_ssh`

This would lead apswitch always use connection plugin "ssh"
In ansible/roles/test/tasks/check_sw_vm_interfaces.yml
```
  - name: Gather Port-Channel status from VMs
    action: apswitch template=roles/vm_set/templates/show_int_portchannel_status.j2
    args:
      host: "{{ vms[item]['mgmt_addr'] }}"
      login: "{{ switch_login[hwsku_map[peer_hwsku]] }}"
    connection: switch
    ignore_errors: yes
    when: vms["{{ item }}"]['hwsku'] == 'Arista-VM'
    with_items: "{{ vms }}"
    register: vm_portchannel_status
```

Would get below error:
```
TASK [test : Gather Port-Channel status from VMs] ******************************
task path: /var/johnar/sonic-mgmt/ansible/roles/test/tasks/check_sw_vm_interfaces.yml:42
Thursday 01 October 2020  07:22:36 +0000 (0:00:00.329)       0:05:46.580 ****** 
[WARNING]: conditional statements should not include jinja2 templating
delimiters such as {{ }} or {% %}. Found: vms["{{ item }}"]['hwsku'] ==
'Arista-VM'
ActionModule run
ssh
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 111, in run
    item_results = self._run_loop(items)
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 371, in _run_loop
    res = self._execute(variables=task_vars)
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 664, in _execute
    result = self._handler.run(task_vars=variables)
  File "/var/johnar/sonic-mgmt/ansible/plugins/action/apswitch.py", line 61, in run
    timeout=_timeout)
TypeError: exec_command() got an unexpected keyword argument 'template'
fatal: [as4630-54pe-2]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```

**Steps to reproduce the issue:**
1. Run ansible Task "Gather Port-Channel status from VMs"

**Describe the results you received:**
```
TASK [test : Gather Port-Channel status from VMs] ******************************
task path: /var/johnar/sonic-mgmt/ansible/roles/test/tasks/check_sw_vm_interfaces.yml:42
Thursday 01 October 2020  07:22:36 +0000 (0:00:00.329)       0:05:46.580 ****** 
[WARNING]: conditional statements should not include jinja2 templating
delimiters such as {{ }} or {% %}. Found: vms["{{ item }}"]['hwsku'] ==
'Arista-VM'
ActionModule run
ssh
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 111, in run
    item_results = self._run_loop(items)
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 371, in _run_loop
    res = self._execute(variables=task_vars)
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 664, in _execute
    result = self._handler.run(task_vars=variables)
  File "/var/johnar/sonic-mgmt/ansible/plugins/action/apswitch.py", line 61, in run
    timeout=_timeout)
TypeError: exec_command() got an unexpected keyword argument 'template'
fatal: [as4630-54pe-2]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```

**Describe the results you expected:**
It should use the connection plugin "switch" to get VM information .

**Comment by wangxin** [comment]
@lolyu Could you take a look?

**Comment by lolyu** [comment]
Hi @chiourung, could you please provide your Ansible playbook run command?

**Comment by chiourung** [comment]
ansible-playbook -i lab --limit as7816-64x test_sonic.yml -e testbed_name=3-10_t0 -e testcase_name=reboot -vvvv

You can run any test case to reproduce the case, but make sure not all port-channels are up and then it would call apswitch to gather port-channel status from VMs

**Comment by lolyu** [comment]
Looks like using `connection: switch` could not override the `ansible_connection` defined in the `sonic` group variable files.
Changing to this could solve this:

```ansible
  - name: Gather Port-Channel status from VMs
    action: apswitch template=roles/vm_set/templates/show_int_portchannel_status.j2
    args:
      host: "{{ vms[item]['mgmt_addr'] }}"
      login: "{{ switch_login[hwsku_map[peer_hwsku]] }}"
    vars:
      ansible_connection: switch
    when: vms["{{ item }}"]['hwsku'] == 'Arista-VM'
    with_items: "{{ vms }}"
    register: vm_portchannel_status
```
I will raise a PR to fix this, thanks.
