### ISSUE TITLE
Tests skipped without adding [-s] using ./run_tests.sh

### ISSUE THREAD

**Issue by stephengzh** [Azure/sonic-mgmt#2559]
**Description**

Hi, I am trying to run all tests based on https://github.com/Azure/sonic-mgmt/blob/master/tests/README.md#run-nightly-tests, but it seems that almost all test scripts are skipped. I don't know why. I didn't add [-s].

**Steps to reproduce the issue:**
1. ./run_tests.sh -d [dut-name] -n t0 -t t0
2.
3.

**Describe the results you received:**

johnar@6dc8f31ae7dd:~/sonic-mgmt/tests$ ./run_tests.sh -d [dut-name] -n t0 -t t0
=== Preparing DUT for subsequent tests ===
======================================================================================= test session starts =======================================================================================
platform linux2 -- Python 2.7.12, pytest-4.6.5, py-1.8.1, pluggy-0.13.1
ansible: 2.8.7
rootdir: /var/johnar/sonic-mgmt
plugins: repeat-0.8.0, xdist-1.28.0, ansible-2.2.2, forked-1.1.3
collected 1126 items / 1120 deselected / 6 selected                                                                                                                                               

test_announce_routes.py::test_announce_routes ^C^C
....

**Describe the results you expected:**
All tests selected.

**Additional information you deem important:**
The selected tests are only test_announce_routes.py, test_pre, test_nbr_health and test_post.
    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by stephengzh** [comment]
When adding '-u' to skip all these util tests. An error appeared:

johnar@6dc8f31ae7dd:~/sonic-mgmt/tests$ ./run_tests.sh -d  [dut-name] -n t0 -u -t t0
=== Running tests in groups ===
WARNING: No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
  File "/usr/local/bin/pytest", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config/__init__.py", line 63, in main
    config = _prepareconfig(args, plugins)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config/__init__.py", line 207, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/helpconfig.py", line 94, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config/__init__.py", line 687, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config/__init__.py", line 901, in parse
    args, self.option, namespace=self.option
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config/argparsing.py", line 101, in parse_setoption
    parsedoption = self.parse(args, namespace=namespace)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config/argparsing.py", line 78, in parse
    self.optparser = self._getparser()
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config/argparsing.py", line 95, in _getparser
    arggroup.add_argument(*n, **a)
  File "/usr/lib/python2.7/argparse.py", line 1308, in add_argument
    return self._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1509, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1322, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python2.7/argparse.py", line 1460, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python2.7/argparse.py", line 1467, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --num_routes: conflicting option string(s): --num_routes

**Comment by 119064273** [comment]
I meet the same question, can you share your fix way?
