### ISSUE TITLE
Running ecmp test

### ISSUE THREAD

**Issue by richawil** [Azure/sonic-mgmt#2612]
**Description**
I am trying to run the ecmp test without success.
I have tried several commands to launch the test, each of which fails in an unexpected way.

**Steps to reproduce the issue:**
1. ansible-playbook test_sonic.yml -vvv -i lab --limit ch1-dut, --become --tags ecmp --extra-vars "testbed_type=t1 vm_hosts=[VM0101,VM0102,VM0103] vm_source={VM0100} [ipv6=True]" | tee /data/testlogs/ecmp/pb.log
This is the way the documentation says to launch the test. 
But the test bails out right after the Gathering Facts task.

2. ansible-playbook test_sonic.yml -vvv -i lab --limit ch1-dut -e testcase_name=ecmp -e testbed_name=chill-t1 --extra-vars "testbed_type=t1 vm_hosts=[VM0110,VM0111,VM0112] vm_source={VM0100} [ipv6=True]"
This command to launch the test goes much further, but eventually fails:
TASK [test : Configure VMs to add loopback interface] *******************************************************
task path: /data/ansible/roles/test/tasks/ecmp.yml:45
Wednesday 02 December 2020  13:04:09 +0000 (0:00:00.192)       0:00:20.656 ****
Using module file /data/ansible/library/configure_vms.py
Pipelining is enabled.
<10.250.0.103> ESTABLISH SSH CONNECTION FOR USER: cisco
<10.250.0.103> SSH: EXEC sshpass -d10 ssh -o ControlMaster=auto -o ControlPersist=120s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o StrictHostKeyChecking=no -o 'User="cisco"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/6b7f686bbd 10.250.0.103 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<10.250.0.103> (1, '', 'Traceback (most recent call last):\n  File "<stdin>", line 114, in <module>\n  File "<stdin>", line 106, in _ansiballz_main\n  File "<stdin>", line 49, in invoke_module\n  File "/tmp/ansible_configure_vms_payload_SKUjwe/__main__.py", line 21, in <module>\nImportError: No module named paramiko\n')

3. py.test saitests/ecmp_test.py --testbed=chill-t1 --inventory=/data/ansible/lab --testbed_file=../ansible/testbed.csv --host-pattern=chill-t1 --module-path=../ansible/library -v
This one also fails:
__________________________________ ERROR collecting saitests/ecmp_test.py ___________________________________
ImportError while importing test module '/data/tests/saitests/ecmp_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
saitests/ecmp_test.py:10: in <module>
    import sai_base_test
saitests/sai_base_test.py:25: in <module>
    import switch_sai_thrift
E   ImportError: No module named switch_sai_thrift

**Describe the results you expected:**
I expected perhaps one of these tests to execute.

**Additional information you deem important:**

    **Output of `show version`:**

    ```
SONiC Software Version: SONiC.master.424-ebdfb4be
Distribution: Debian 10.4
Kernel: 4.19.0-9-2-amd64
Build commit: ebdfb4be
Build date: Wed Jul 22 17:17:01 UTC 2020
Built by: johnar@jenkins-worker-9

Platform: x86_64-kvm_x86_64-r0
HwSKU: Force10-S6000
ASIC: vs
Serial Number: 000000
Uptime: 17:37:45 up 1 day, 3:58, 1 user, load average: 1.83, 2.74, 3.33
    ```

**Comment by stephengzh** [comment]
E ImportError: No module named switch_sai_thrift
↑
I met this error before. It is because the missing of some lib files.

My solution:
1. In your ptf docker:

git clone https://github.com/opencomputeproject/SAI.git

2. And then:

cd  SAI/test/saithrift/

3. Install the SAI thrift client library :
python setup.py install

After that, run your test case command again and see the result.

**Comment by richawil** [comment]
Got an error during the installation of the SAI thrift client library:
root@2b113d82fca5:~/SAI/test/saithrift# python setup.py install
running install
running build
running build_py
error: package directory 'src/gen-py/switch_sai' does not exist

**Comment by 119064273** [comment]
@richawil  have you fix the error of "error: package directory 'src/gen-py/switch_sai' does not exist" ? i also meet it

**Comment by 119064273** [comment]
@yxieca  can you give some advice ?

**Comment by yxieca** [comment]
@richawil AFAIK, ansible test is only meant to run against 201811 or earlier images. For newer images, you should run the test with pytest.
saitests/ecmp_test.py is not a pytest file, this is a helper test script invoked by ptfrunner or ptfadapter.
You should run tests/ecmp instead.

**Comment by 119064273** [comment]
> @richawil AFAIK, ansible test is only meant to run against 201811 or earlier images. For newer images, you should run the test with pytest.
> saitests/ecmp_test.py is not a pytest file, this is a helper test script invoked by ptfrunner or ptfadapter.
> You should run tests/ecmp instead.

but when i run tests/qos/test_qos_sai.py  ,  it need module of "switch_sai_thrift", current ptf not include it, how do you test it?
