### ISSUE TITLE
IOError seen running spytest/tests/system/test_ssh.py

### ISSUE THREAD

**Issue by richawil** [Azure/sonic-mgmt#3051]
**Description**

Problem is seen when running the spytest/tests/system/test_ssh.py using the 2 DUT topology.
We see and IOError when trying to check if DUT 2 has the sshpass program installed.
**Steps to reproduce the issue:**
1. Run spytest test.ssh.py

**Describe the results you received:**
  File "/home/vxr/sonic-test/sonic-mgmt/spytest/spytest/access/sonic_connection.py", line 462, in send_command_new
    raise IOError(self.dmsg_str(dbg_msg, msg1))
IOError: Search pattern: ‘admin\@sonic\:\~\$' never detected

**Describe the results you expected:**
Code was looking for the SONiC prompt on the DUT.  But it actually found the prompt from the vty shell in configuration mode.

**Additional information you deem important:**

2021-02-26 18:52:18,209 T0000: INFO  connecting to device with default username=admin,password=admin
2021-02-26 18:52:18,209 T0000: ERROR RW: rexec_ssh: dev=SD2 addr=2.2.3.1 user=admin command=show vlan config
2021-02-26 18:52:18,209 T0000: ERROR prompt=cisco\@sonic\:\~\$
2021-02-26 18:52:18,209 T0000: ERROR RW: send_cmd=which sshpass expect=admin\@sonic\:\~\$
2021-02-26 18:52:18,209 T0000: INFO  [D2-SD2] FCMD: which sshpass
2021-02-26 18:52:18,210 T0000: INFO  [D2-SD2] EXPECT: admin\@sonic\:\~\$
2021-02-26 18:55:38,845 T0000: WARN  [D2-SD2] cmd: which sshpass attempt 0 ref: 5107
2021-02-26 18:55:38,848 T0000: ERROR Exception at 1474
2021-02-26 18:55:38,849 T0000: ERROR Traceback (most recent call last):
  File "/home/vxr/sonic-test/sonic-mgmt/spytest/spytest/net.py", line 1468, in _try
    output = hndl.send_command_new(fcli, cmd, expect_string, delay_factor, **kwargs)
  File "/home/vxr/sonic-test/sonic-mgmt/spytest/spytest/access/sonic_connection.py", line 462, in send_command_new
    raise IOError(self.dmsg_str(dbg_msg, msg1))
IOError: Search pattern: ‘admin\@sonic\:\~\$' never detected
=======================FASTER-CLI-DBG===================
command_string: which sshpass<LF>
search_pattern: admin\@sonic\:\~\$
cmd_issued: False
CMP-OUT: which sshpass<LF>% Unknown command: which sshpass<LF>sonic(config)#
CMP-CMD: which sshpass<LF>
ECHOED  output: % Unknown command: which sshpass<LF>sonic(config)#
CMP-PROMPT: admin\@sonic\:\~\$
CMP-OUTPUT: % Unknown command: which sshpass<LF>sonic(config)#
Read Data:  which sshpass<CR>
Read Data:  % Unknown command: which sshpass<CR>
Read Data:  sonic(config)#
==========================================================

I think the problem is that a previous command left the D2-SD2 device console in the vtysh config mode.
So when the code tries to check/install sshpass, the command
	sonic(config)# which sshpass
fails when run at prompt the vtysh prompt.

It appears the last command run on D2-SD2 was to delete a static route:

2021-02-26 18:51:55,696 T0000: INFO  RW: delete_staic_route: next_hop=192.168.122.1 ip=0.0.0.0/0 hell=sonic
2021-02-26 18:51:55,696 T0000: INFO  shell parameter is obsolete and will be ignored. Please use cli_type.
2021-02-26 18:51:55,696 T0000: INFO  CLI type click
2021-02-26 18:51:55,696 T0000: INFO  New CLI type vtysh
2021-02-26 18:51:55,696 T0000: ERROR RW: net-config: opts={'ctype': 'vtysh', 'exec_mode': None, 'skip_tmpl': False, 'skip_error_check': False, 'expect_reboot': False, 'expect_ipchange': False, 'max_time': 0, 'sudo': False, 'sep': u'\n', 'conf': True, 'confirm': None, 'faster_cli': True, 'trace_log': 3, 'delay_factor': 0, 'cmds_delay_factor': 3} cmds=['no ip route 0.0.0.0/0 192.168.122.1'] dev=SD2
2021-02-26 18:51:55,898 T0000: ERROR RW: send_cmd=sudo vtysh expect=(sonic|sonic)#
2021-02-26 18:51:55,898 T0000: INFO  [D2-SD2] FCMD: sudo vtysh
2021-02-26 18:51:55,898 T0000: INFO  [D2-SD2] EXPECT: (sonic|sonic)#
2021-02-26 18:51:56,502 T0000: INFO  [D2-SD2]
2021-02-26 18:51:56,502 T0000: INFO  [D2-SD2] Hello, this is FRRouting (version 7.5-sonic).
2021-02-26 18:51:56,502 T0000: INFO  [D2-SD2] Copyright 1996-2005 Kunihiro Ishiguro, et al.
2021-02-26 18:51:56,502 T0000: INFO  [D2-SD2]
2021-02-26 18:51:56,503 T0000: INFO  [D2-SD2] sonic#
2021-02-26 18:51:56,503 T0000: ERROR RW: send_cmd=configure terminal expect=(sonic|sonic)\(config\)#
2021-02-26 18:51:56,503 T0000: INFO  [D2-SD2] FCMD: configure terminal
2021-02-26 18:51:56,503 T0000: INFO  [D2-SD2] EXPECT: (sonic|sonic)\(config\)#
2021-02-26 18:51:56,555 T0000: INFO  [D2-SD2] sonic(config)#
2021-02-26 18:51:56,756 T0000: ERROR RW: send_cmd=no ip route 0.0.0.0/0 192.168.122.1 expect=(sonic|sonic)\(config[^)]*\)#
2021-02-26 18:51:56,757 T0000: INFO  [D2-SD2] FCMD: no ip route 0.0.0.0/0 192.168.122.1
2021-02-26 18:51:56,757 T0000: INFO  [D2-SD2] EXPECT: (sonic|sonic)\(config[^)]*\)#
2021-02-26 18:51:56,808 T0000: INFO  [D2-SD2] sonic(config)#
2021-02-26 18:51:56,809 T0000: INFO  Ensure service parameter(s) - snmptrap -> ip
2021-02-26 18:51:56,809 T0000: INFO  Return : 172.27.147.152
2021-02-26 18:51:56,809 T0000: INFO  ACL_DATA: {'ACL_TABLE': {'V6_SSH_ONLY': {'services': ['SSH'], 'type': 'CTRLPLANE', 'policy_desc': 'V6_SSH_ONLY'}, 'SNMP_SSH': {'services': ['SNMP', 'SSH'], 'type': 'CTRLPLANE', 'policy_desc': 'SNMP_SSH'}}, 'ACL_RULE': {'SNMP_SSH|DEFAULT_RULE100': {'PRIORITY': '1', 'PACKET_ACTION': 'DROP', 'L4_DST_PORT': '22', 'ETHER_TYPE': '0x0800'}, 'SNMP_SSH|DEFAULT_RULE101': {'PRIORITY': '2', 'PACKET_ACTION': 'DROP', 'L4_DST_PORT': '161', 'IP_PROTOCOL': '17'}, 'V6_SSH_ONLY|RULE_1': {'PACKET_ACTION': 'ACCEPT', 'PRIORITY': '9996', 'SRC_IPV6': '1001::0/64', 'IP_PROTOCOL': '6', 'L4_DST_PORT': '22'}, 'V6_SSH_ONLY|DEFAULT_RULE100': {'PRIORITY': '3', 'PACKET_ACTION': 'DROP', 'L4_DST_PORT': '22', 'ETHER_TYPE': '0x86dd'}, 'SNMP_SSH|RULE_1': {'PRIORITY': '9997', 'PACKET_ACTION': 'ACCEPT', 'SRC_IP': '172.27.147.152/32', 'IP_PROTOCOL': '17'}, 'SNMP_SSH|RULE_3': {'PRIORITY': '9998', 'PACKET_ACTION': 'ACCEPT', 'SRC_IP': '2.2.2.0/24', 'L4_DST_PORT': '22', 'IP_PROTOCOL': '6'}, 'SNMP_SSH|RULE_2': {'PRIORITY': '9999', 'PACKET_ACTION': 'ACCEPT', 'SRC_IP': '172.27.147.152/32', 'IP_PROTOCOL': '6'}}}
2021-02-26 18:51:57,212 T0000: ERROR RW: send_cmd=end
exit expect=([#|\$]\s*$)
2021-02-26 18:51:57,213 T0000: INFO  [D1-SD1] SCMD: end\nexit
2021-02-26 18:51:57,213 T0000: INFO  [D1-SD1] EXPECT: ([#|\$]\s*$)
2021-02-26 18:51:58,015 T0000: INFO  [D1-SD1]
2021-02-26 18:51:58,015 T0000: INFO  [D1-SD1] sonic# exit

Note that the command to end\nexit from the sonic(config)# mode was applied to D1-SD1. But it was D2-SD2 which was in this mode.
    **Output of `show version`:**

    ```
SONiC Software Version: SONiC.cisco_202012.18-dirty-20210221.222236
Distribution: Debian 10.8
Kernel: 4.19.0-9-cisco-amd64
Build commit: 5b2fc65b
Build date: Mon Feb 22 05:52:42 UTC 2021
Built by: jenkins@mb12-004

Platform: x86_64-8201_sys-r0
HwSKU: 36x100Gb
ASIC: cisco-8000
ASIC Count: 1
Serial Number: b'FOC2219IIMA'
Cisco-SONiC Build ID: 1947
Cisco Silicon One SDK: 1.37.0-SDK-1.7.1-ga04e944-sai-debug-shell-cpu-hog-fix-1
Cisco Whitebox BSP: 0.2.1-26-gf07caed
Cisco Whitebox FPD: 0.1-63-g83b4c82
Cisco NP Suite: 1.70.0
Uptime: 21:14:05 up 1 day,  8:15,  1 user,  load average: 3.10, 3.36, 3.47
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yxieca** [comment]
@ramakristipati please help.
