### ISSUE TITLE
There is no management interface in neighbor

### ISSUE THREAD

**Issue by AndoniSanguesa** [Azure/sonic-mgmt#3714]
**Description**
After updating to the latest version of the sonic-mgmt repo, the `test_nbr_health.py` test failed. The error message indicated that there is no management interface in the leaf nodes. This was confirmed by running the `show management_interface address` command. 

**Steps to reproduce the issue:**
1. Clone sonic-mgmt repo as of this #3481
2. Configure KVM testbed w/ SONiC leaf nodes
3. Run any pytest from the container : `./run_tests.sh -n vms-kvm-t0 -d vlab-01 -c bgp/test_bgp.py -f vtestbed.csv -i veos_vtb -e "--neighbor_type=sonic"`

**Describe the results you received:**
Result from `test_nbr_health.py`:
```
>       pytest_assert(len(fails) == 0, "\n".join(fails))
E       Failed: there is no management interface in neighbor ARISTA04T1
E       there is no management interface in neighbor ARISTA03T1
E       there is no management interface in neighbor ARISTA02T1
E       there is no management interface in neighbor ARISTA01T1

config_facts = {'ACL_TABLE': {'DATAACL': {'policy_desc': u'DATAACL', 'ports': [u'PortChannel0001', u'PortChannel0002', u'PortChannel0...0_300m_profile]'}}, 'Ethernet108': {'3-4': {'profile': u'[BUFFER_PROFILE|pg_lossless_40000_300m_profile]'}}, ...}, ...}
dev_meta   = {'localhost': {'bgp_asn': u'65100', 'buffer_model': u'traditional', 'cloudtype': u'None', 'default_bgp_status': u'up', ...}}
dut_type   = u'ToRRouter'
duthost    = <MultiAsicSonicHost> vlab-01
duthosts   = <tests.common.devices.duthosts.DutHosts object at 0x7f61338fa450>
enum_frontend_dut_hostname = 'vlab-01'
eos        = {'bgp_gr_timer': 700, 'ceos_image_mount_dir': '/data/ceos', 'snmp_location': 'str', 'snmp_rocommunity': 'strcommunity'}
failmsg    = None
fails      = ['there is no management interface in neighbor ARISTA04T1', 'there is no management interface in neighbor ARISTA03T1', 'there is no management interface in neighbor ARISTA02T1', 'there is no management interface in neighbor ARISTA01T1']
k          = 'ARISTA01T1'
localhost  = <tests.common.devices.local.Localhost object at 0x7f6132205510>
nbrhost    = <tests.common.devices.sonic.SonicHost object at 0x7f61339caa50>
nbrhosts   = {'ARISTA01T1': {'conf': {'bgp': {'asn': 64600, 'peers': {65100: ['10.0.0.56', 'FC00::71']}}, 'bp_interface': {'ipv4': ... 'fc00::7e/126'}}, 'properties': ['common']}, 'host': <tests.common.devices.sonic.SonicHost object at 0x7f61333d2c10>}}
nei_meta   = {'ARISTA01T1': {'hwsku': u'Arista-VM', 'lo_addr': u'None', 'mgmt_addr': u'10.250.0.51', 'type': u'LeafRouter'}, 'ARIST...outer'}, 'ARISTA04T1': {'hwsku': u'Arista-VM', 'lo_addr': u'None', 'mgmt_addr': u'10.250.0.54', 'type': u'LeafRouter'}}
sonic      = {'snmp_rocommunity': 'public'}
v          = {'hwsku': u'Arista-VM', 'lo_addr': u'None', 'mgmt_addr': u'10.250.0.51', 'type': u'LeafRouter'}
```
`show management_interfaces address` results in no output if run on the leaf:

```
admin@VM0103:~$ show management_interface address
admin@VM0103:~$
```

**Describe the results you expected:**

`show management_interfaces address` results in the expected output if run on the DUT:
```
admin@vlab-01:~$ show management_interface address

Management IP address = 10.250.0.101/24
Management Network Default Gateway = 10.250.0.1
Management IP address = fec0::ffff:afa:1/64
Management Network Default Gateway = fec0::1
```

**Additional information you deem important:**
The `/etc/sonic/config_db.json` config file does show the mangement port configured:

```
    "MGMT_INTERFACE": {
        "eth0|10.250.0.54/24": {
            "gwaddr": "10.250.0.1"
        }
    },
    "MGMT_PORT": {
        "eth0": {
            "alias": "eth0",
            "admin_status": "up"
        }
    }
```

**Output of `show version`:**

```
SONiC Software Version: SONiC.master.21432-2483860fd
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: 2483860fd
Build date: Sat Jun 26 13:07:58 UTC 2021
Built by: AzDevOps@sonic-build-workers-000F7S

Platform: x86_64-kvm_x86_64-r0
HwSKU: Force10-S6000
ASIC: vs
ASIC Count: 1
Serial Number: None
Model Number: None
Hardware Revision: None
Uptime: 23:57:16 up  4:35,  1 user,  load average: 8.02, 8.84, 9.43

Docker images:
REPOSITORY                    TAG                      IMAGE ID            SIZE
docker-platform-monitor       latest                   ee885c804c58        627MB
docker-platform-monitor       master.21432-2483860fd   ee885c804c58        627MB
docker-gbsyncd-vs             latest                   31137a87e49d        419MB
docker-gbsyncd-vs             master.21432-2483860fd   31137a87e49d        419MB
docker-syncd-vs               latest                   28ce1cf8cec2        419MB
docker-syncd-vs               master.21432-2483860fd   28ce1cf8cec2        419MB
docker-dhcp-relay             latest                   4c4a6bebdeb9        420MB
docker-dhcp-relay             master.21432-2483860fd   4c4a6bebdeb9        420MB
docker-nat                    latest                   9a871e21492a        427MB
docker-nat                    master.21432-2483860fd   9a871e21492a        427MB
docker-teamd                  latest                   85fbde70ed0d        424MB
docker-teamd                  master.21432-2483860fd   85fbde70ed0d        424MB
docker-snmp                   latest                   d5143b6c45b0        454MB
docker-snmp                   master.21432-2483860fd   d5143b6c45b0        454MB
docker-lldp                   latest                   aa0853ef7c51        453MB
docker-lldp                   master.21432-2483860fd   aa0853ef7c51        453MB
docker-router-advertiser      latest                   d12bde4a00f5        413MB
docker-router-advertiser      master.21432-2483860fd   d12bde4a00f5        413MB
docker-macsec                 latest                   c6ea578247f2        427MB
docker-macsec                 master.21432-2483860fd   c6ea578247f2        427MB
docker-database               latest                   4367c123d2bb        413MB
docker-database               master.21432-2483860fd   4367c123d2bb        413MB
docker-orchagent              latest                   b9e567be50dd        442MB
docker-orchagent              master.21432-2483860fd   b9e567be50dd        442MB
docker-sonic-mgmt-framework   latest                   0ef64fc2f2b9        570MB
docker-sonic-mgmt-framework   master.21432-2483860fd   0ef64fc2f2b9        570MB
docker-sonic-telemetry        latest                   f67ff7b00dbb        501MB
docker-sonic-telemetry        master.21432-2483860fd   f67ff7b00dbb        501MB
docker-sflow                  latest                   e99e674ef98b        425MB
docker-sflow                  master.21432-2483860fd   e99e674ef98b        425MB
docker-fpm-frr                latest                   4b662489cf58        442MB
docker-fpm-frr                master.21432-2483860fd   4b662489cf58        442MB
```

**Attach debug file `sudo generate_dump`:**
[sonic_dump_vlab-01_20210629_151657.tar.gz](https://github.com/Azure/sonic-mgmt/files/6734621/sonic_dump_vlab-01_20210629_151657.tar.gz)

Thanks for your help.

**Comment by AndoniSanguesa** [comment]
If I copy the minigraph template over and run `sudo configure load_minigraph -y` myself, I get the following error:

```
admin@VM0102:~$ sudo config load_minigraph -y
Disabling container monitoring ...
Stopping SONiC target ...
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json   --write-to-db
Traceback (most recent call last):
  File "/usr/local/bin/sonic-cfggen", line 452, in <module>
    main()
  File "/usr/local/bin/sonic-cfggen", line 348, in main
    deep_update(data, parse_xml(minigraph, platform, asic_name=asic_name))
  File "/usr/local/lib/python3.7/dist-packages/minigraph.py", line 1241, in parse_xml
    device_type = [devices[key]['type'] for key in devices if key.lower() == hostname.lower()][0]
TypeError: 'NoneType' object is not iterable
```

**Comment by AndoniSanguesa** [comment]
The issue appears to not be in the sonic-mgmt repo. I resolved the issue by rolling back the SONiC build image version. If anyone runs into this error this is the build I'm using build (52c7218)[https://dev.azure.com/mssonic/build/_build/results?buildId=20135&view=results]
