### ISSUE TITLE
using the docker-sonic-mgmt run the test such as fib occur some error

### ISSUE THREAD

**Issue by huanchen** [Azure/sonic-mgmt#387]
using the docker-sonic-mgmt run the test such as fib occur some error：

the docker for ptf and sonic-mgmt  are build in Dec  as following the Guide for Test

When run the test tags fib or bgp，the step of FIB test，using PTF  create packets and send，there occur some issue：

TASK [test : PTF Test - FIB test] **********************************************
Tuesday 12 December 2017  16:56:31 +0000 (0:00:00.094)       0:01:12.636 ****** 
ok: [dut-nephos-01] => {
    "msg": "ptf --test-dir ptftests fib_test.FibTest   --platform-dir ptftests  --platform remote  -t \"testbed_type='t1';router_mac='6c:ec:5a:08:15:c4';fib_info='/root/fib_info.txt';ipv4=True;ipv6=True\"  --relax --debug info --log-file /tmp/fib_test.FibTest.ipv4.True.ipv6.True.2000-06-07T20:58:16Z.log  --disable-vxlan --disable-geneve --disable-erspan --disable-mpls --disable-nvgre 2>&1"
}

TASK [test : command] **********************************************************
Tuesday 12 December 2017  16:56:31 +0000 (0:00:00.132)       0:01:12.768 ****** 
changed: [dut-nephos-01 -> 10.250.0.178]

TASK [test : debug] ************************************************************
Tuesday 12 December 2017  16:56:37 +0000 (0:00:05.933)       0:01:18.702 ****** 
ok: [dut-nephos-01] => {
    "out.stdout_lines": [
        "WARNING: Failed to execute tcpdump. Check it is installed and in the PATH", 
        "WARNING: No route found for IPv6 destination :: (no default route?)", 
        "fib_test.FibTest ... FAIL", 
        "", 
        "======================================================================", 
        "FAIL: fib_test.FibTest", 
        "----------------------------------------------------------------------", 
        "Traceback (most recent call last):", 
        "  File \"ptftests/fib_test.py\", line 279, in runTest", 
        "    self.check_ip_range()", 
        "  File \"ptftests/fib_test.py\", line 124, in check_ip_range", 
        "    self.check_ip_route(src_port, ip_range.get_first_ip(), exp_port_list, ipv4)", 
        "  File \"ptftests/fib_test.py\", line 144, in check_ip_route", 
        "    (matched_index, received) = self.check_ipv4_route(src_port, dst_ip_addr, dst_port_list)", 
        "  File \"ptftests/fib_test.py\", line 189, in check_ipv4_route", 
        "    return verify_packet_any_port(self, masked_exp_pkt, dst_port_list)", 
        "  File \"/usr/lib/python2.7/dist-packages/ptf/testutils.py\", line 2373, in verify_packet_any_port", 
        "    % (ports, device_number, result.format()))", 
        "AssertionError: Did not receive expected packet on any of ports [8, 9, 2, 3, 0, 1, 6, 7, 4, 5, 14, 15, 10, 11, 12, 13] for device 0.", 

I has try it in the ptf docker, the cmd is that  
.. ptf --test-dir ptftests fib_test.FibTest   --platform-dir ptftests  --platform remote  -t \"testbed_type='t1';router_mac='6c:ec:5a:08:15:c4';fib_info='/root/fib_info.txt';ipv4=True;ipv6=True\"

it return info:

ipv6=True\"
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
WARNING: No route found for IPv6 destination :: (no default route?)
fib_test.FibTest ... ERROR

======================================================================
ERROR: fib_test.FibTest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ptftests/fib_test.py", line 86, in setUp
    self.fib = fib.Fib(self.test_params['fib_info'])
KeyError: 'fib_info'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)

******************************************
ATTENTION: SOME TESTS DID NOT PASS!!!

The following tests errored:
FibTest

the var "fib_info" is define and  the file /root/fib_info.txt is existed.

has someone attach same problem, how to resolved it  ,pls share, thinks.

**Comment by huanchen** [comment]
when i run the acl test ， the issue is existed yet。

ansible-playbook -i lab --limit dut-nephos-01 test_sonic.yml --tags acl --extra-vars "testbed_type=t1 ptf_host=10.250.0.178 run_dir=/tmp"

TASK [test : PTF Test - ACL Test] **********************************************
Tuesday 12 December 2017  23:09:59 +0000 (0:00:00.077)       0:02:28.506 ****** 
ok: [dut-nephos-01] => {
    "msg": "ptf --test-dir acstests acltb_test.AclTest   --platform remote  -t \"verbose=True;router_mac=\\\"6c:ec:5a:08:15:c4\\\";switch_info=\\\"/tmp/acltb_switch_info.txt\\\"\"   --disable-vxlan --disable-geneve --disable-erspan --disable-mpls --disable-nvgre 2>&1"
}

TASK [test : command] **********************************************************
Tuesday 12 December 2017  23:09:59 +0000 (0:00:00.129)       0:02:28.635 ****** 
changed: [dut-nephos-01 -> 10.250.0.178]

TASK [test : debug] ************************************************************
Tuesday 12 December 2017  23:10:11 +0000 (0:00:11.540)       0:02:40.175 ****** 
ok: [dut-nephos-01] => {
    "out.stdout_lines": [
        "WARNING: Failed to execute tcpdump. Check it is installed and in the PATH", 
        "WARNING: No route found for IPv6 destination :: (no default route?)", 
        "acltb_test.AclTest ... FAIL", 
        "", 
        "======================================================================", 
        "FAIL: acltb_test.AclTest", 
        "----------------------------------------------------------------------", 
        "Traceback (most recent call last):", 
        "  File \"acstests/acltb_test.py\", line 262, in runTest", 
        "    assert(tests_passed == tests_total)", 
        "AssertionError", 
        "", 
        "----------------------------------------------------------------------", 
        "Ran 1 test in 10.066s", 
        "", 
        "FAILED (failures=1)"
    ]
}

#copy the comand  and run it in docker-ptf

root@57022ff0ed9e:~# ptf --test-dir acstests acltb_test.AclTest   --platform remote  -t \"verbose=True;router_mac=\\\"6c:ec:5a:08:15:c4\\\";switch_info=\\\"/tmp/acltb_switch_info.txt\\\"\"   --disable-vxlan --disable-geneve --disable-erspan --disable-mpls --disable-nvgre
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
WARNING: No route found for IPv6 destination :: (no default route?)
acltb_test.AclTest ... ERROR

======================================================================
ERROR: acltb_test.AclTest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "acstests/acltb_test.py", line 60, in setUp
    self.router_mac = self.test_params['router_mac']
KeyError: 'router_mac'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)

******************************************
ATTENTION: SOME TESTS DID NOT PASS!!!

The following tests errored:
AclTest

******************************************
-bash: --disable-vxlan: command not found
