### ISSUE TITLE
Analyze/fix tacacs/test_ro_disk.py::test_ro_disk

### ISSUE THREAD

**Issue by StormLiangMS** [Azure/sonic-mgmt#4172]
**Description**
Test failure seen on T0 @ 2nd September run with  
20201231.22

below is the stack trace for this issue:  
tacacs/test_ro_disk.py::test_ro_disk
-------------------------------- live log call ---------------------------------
18:51:39 __init__.pytest_runtest_call             L0039 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call
    testfunction(**testargs)
  File "/azp/agent/_work/25/s/tests/tacacs/test_ro_disk.py", line 89, in test_ro_disk
    rw_user, rw_pass, "cat /etc/passwd"), "Failed to ssh upon reboot"
AssertionError: Failed to ssh upon reboot  
**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by abdosi** [comment]
fix with https://github.com/Azure/sonic-mgmt/pull/4180

**Comment by abdosi** [comment]
cc @SuvarnaMeenakshi
