### ISSUE TITLE
Investigate/fix test_show_platform_ssdhealth failure

### ISSUE THREAD

**Issue by neethajohn** [Azure/sonic-mgmt#4786]
Regression on .44. Testcase was passing till .43
```
admin@str2-7050qx-32s-acs-02:~$ show platform ssdhealth      
Traceback (most recent call last):
  File "/usr/local/bin/ssdutil", line 8, in <module>
    sys.exit(ssdutil())
  File "/usr/local/lib/python3.7/dist-packages/ssdutil/main.py", line 68, in ssdutil
    ssd = import_ssd_api(args.device)
  File "/usr/local/lib/python3.7/dist-packages/ssdutil/main.py", line 47, in import_ssd_api
    return SsdUtil(diskdev)
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform_base/sonic_ssd/ssd_generic.py", line 48, in __init__
    self.parse_generic_ssd_info()
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform_base/sonic_ssd/ssd_generic.py", line 80, in parse_generic_ssd_info
    self.model = self._parse_re('Device Model:\s*(.+?)\n', self.ssd_info)
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform_base/sonic_ssd/ssd_generic.py", line 72, in _parse_re
    res_list = re.findall(pattern, buffer)
  File "/usr/lib/python3.7/re.py", line 223, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object
```

**Comment by neethajohn** [comment]
Checking with Vaibhav. D

**Comment by neethajohn** [comment]
https://github.com/Azure/sonic-buildimage/issues/9407
