### ISSUE TITLE
[chassis] test_show_interfaces_counter broken for multi-asic linecards in a T2 chassis

### ISSUE THREAD

**Issue by mannytaheri** [Azure/sonic-mgmt#5191]
**Description**
test_show_interfaces_counter broken for multi-asic linecards in a T2 chassis
This could be related to issue #5141 (gen-mg broken for multi-asic linecards in a T2 chassis) 

**Steps to reproduce the issue:**
1.  Run the test case:  iface_namingmode/test_iface_namingmode.py::TestShowInterfaces::test_show_interfaces_counter

**Describe the results you received:**
def test_show_interfaces_counter(self, setup, setup_config_mode):
        """
        Checks whether 'show interfaces counter' lists the interface names
        as per the configured naming mode
        """
        dutHostGuest, mode, ifmode = setup_config_mode
        regex_int = re.compile(r'(\S+)(\d+)')
        interfaces = list()
    
        show_intf_counter = dutHostGuest.shell('SONIC_CLI_IFACE_MODE={} show interfaces counter'.format(ifmode))
        logger.info('show_intf_counter:\n{}'.format(show_intf_counter['stdout']))
    
        for line in show_intf_counter['stdout_lines']:
            line = line.strip()
            if regex_int.match(line):
                interfaces.append(regex_int.match(line).group(0))
    
        assert(len(interfaces) > 0)
    
        for item in interfaces:
            if mode == 'alias':
>               assert item in setup['port_alias']
E               AssertionError

[1m[31mERROR   [0m root:__init__.py:40 Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 1464, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/python.py", line 174, in pytest_pyfunc_call
    testfunction(**testargs)
  File "/data/tests/iface_namingmode/test_iface_namingmode.py", line 274, in test_show_interfaces_counter
    assert item in setup['port_alias']
AssertionError

**Describe the results you expected:**
No assertion errors

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by mannytaheri** [comment]
Not reproducible
