### ISSUE TITLE
run test when running all the tests fails

### ISSUE THREAD

**Issue by arlakshm** [Azure/sonic-mgmt#5280]
**Description**

**Steps to reproduce the issue:**
The run_test fails with the below error when we run to execute all the tests
```
/usr/local/lib/python2.7/dist-packages/py/_path/common.py:383: in visit 
for x in Visitor(fil, rec, ignore, bf, sort).gen(self): 
/usr/local/lib/python2.7/dist-packages/py/_path/common.py:435: in gen 
for p in self.gen(subdir): 
/usr/local/lib/python2.7/dist-packages/py/_path/common.py:425: in gen 
if p.check(dir=1) and (rec is None or rec(p))]) 
/usr/local/lib/python2.7/dist-packages/_pytest/main.py:667: in _recurse 
ihook = self.gethookproxy(dirpath) 
/usr/local/lib/python2.7/dist-packages/_pytest/main.py:482: in gethookproxy 
my_conftestmodules = pm._getconftestmodules(fspath) 
/usr/local/lib/python2.7/dist-packages/_pytest/config/__init__.py:424: in _getconftestmodules 
mod = self._importconftest(conftestpath.realpath()) 
/usr/local/lib/python2.7/dist-packages/_pytest/config/__init__.py:463: in _importconftest 
raise ConftestImportFailure(conftestpath, sys.exc_info()) 
E ConftestImportFailure: (local('/azp/agent/_work/17/s/tests/ecmp/inner_hashing/conftest.py'), (<type 'exceptions.ImportError'>, ImportError('No module named allure',), <traceback object at 0x7f7586c33870>)) 
------- generated xml file: /azp/agent/_work/17/s/tests/logs/pretest.xml ------- 
Traceback (most recent call last): 
File "/usr/lib/python2.7/logging/__init__.py", line 889, in emit 
stream.write(fs % msg) 
File "/usr/local/lib/python2.7/dist-packages/_pytest/capture.py", line 441, in write 
self.buffer.write(obj) 
ValueError: I/O operation on closed file 
Logged from file __init__.py, line 64 

```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by AntonHryshchuk** [comment]
@arlakshm 
can you please run the test again in your environment, but before execute the command:
 "ln -s /var/AzDevOps/.local/ /root/.local" ?

**Comment by AntonHryshchuk** [comment]
IMO, the root cause in changes here:
#4752 
#4914
