### ISSUE TITLE
KeyError: 'target_dest_mac'  during run vrf tests

### ISSUE THREAD

**Issue by oleksandrKovtunenko** [Azure/sonic-mgmt#5763]
**Description**

I run test ./run_tests.sh -n jss-t0 -c "vrf/test_vrf.py::TestVrfNeigh::test_vrf1_neigh_ip_fwd" and got error KeyError: 'target_dest_mac'

**Steps to reproduce the issue:**
1.  ./run_tests.sh -n jss-t0 -c "vrf/test_vrf.py::TestVrfNeigh::test_vrf1_neigh_ip_fwd"

**Describe the results you received:**
05:45:20 ptf_runner.ptf_runner                    L0079 ERROR  | Exception caught while executing case: vrf_test.FwdTest. Error message: Traceback (most recent call last):
  File "/data/sonic-mgmt-akovtunenko-test/tests/ptf_runner.py", line 72, in ptf_runner
    result = host.shell(cmd, chdir="/root", module_ignore_errors=module_ignore_errors)
  File "/data/sonic-mgmt-akovtunenko-test/tests/common/devices/base.py", line 89, in _run
    raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
RunAnsibleModuleFail: run module shell failed, Ansible Results =>
{
    "changed": true, 
    "cmd": "ptf --test-dir ptftests vrf_test.FwdTest --platform-dir ptftests --platform remote -t 'testbed_type='\"'\"'t0'\"'\"';router_macs=[u'\"'\"'1c:34:da:2f:ab:c0'\"'\"'];fib_info_files=['\"'\"'/tmp/vrf1_neigh.txt'\"'\"'];src_ports=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 28, 29];ptf_test_port_map='\"'\"'/root/ptf_test_port_map.json'\"'\"'' --relax --debug info --log-file /tmp/TestVrfNeigh.test_vrf1_neigh_ip_fwd.log --socket-recv-size 16384", 
    "delta": "0:00:01.904119", 
    "end": "2022-06-06 05:45:20.761276", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "_raw_params": "ptf --test-dir ptftests vrf_test.FwdTest --platform-dir ptftests --platform remote -t 'testbed_type='\"'\"'t0'\"'\"';router_macs=[u'\"'\"'1c:34:da:2f:ab:c0'\"'\"'];fib_info_files=['\"'\"'/tmp/vrf1_neigh.txt'\"'\"'];src_ports=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 28, 29];ptf_test_port_map='\"'\"'/root/ptf_test_port_map.json'\"'\"'' --relax --debug info --log-file /tmp/TestVrfNeigh.test_vrf1_neigh_ip_fwd.log --socket-recv-size 16384", 
            "_uses_shell": true, 
            "argv": null, 
            "chdir": "/root", 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "stdin_add_newline": true, 
            "strip_empty_ends": true, 
            "warn": true
        }
    }, 
    "msg": "non-zero return code", 
    "rc": 1, 
    "start": "2022-06-06 05:45:18.857157", 
    "stderr": "WARNING: No route found for IPv6 destination :: (no default route?)\nptftests/macsec.py:3: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.\n  import cryptography.exceptions\nvrf_test.FwdTest ... ERROR\n\n======================================================================\nERROR: vrf_test.FwdTest\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"ptftests/vrf_test.py\", line 101, in runTest\n    self.check_fwd_entries()\n  File \"ptftests/vrf_test.py\", line 90, in check_fwd_entries\n    self.check_ip_range(ip_range, next_hop, ipv4)\n  File \"ptftests/fib_test.py\", line 204, in check_ip_range\n    self.check_ip_route(src_port, dst_ip, exp_ports, ipv4)\n  File \"ptftests/fib_test.py\", line 237, in check_ip_route\n    res = self.check_ipv4_route(src_port, dst_ip_addr, dst_port_list)\n  File \"ptftests/fib_test.py\", line 267, in check_ipv4_route\n    router_mac = self.ptf_test_port_map[str(src_port)]['target_dest_mac']\nKeyError: 'target_dest_mac'\n\n----------------------------------------------------------------------\nRan 1 test in 0.007s\n\nFAILED (errors=1)", 
    "stderr_lines": [
        "WARNING: No route found for IPv6 destination :: (no default route?)", 
        "ptftests/macsec.py:3: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.", 
        "  import cryptography.exceptions", 
        "vrf_test.FwdTest ... ERROR", 
        "", 
        "======================================================================", 
        "ERROR: vrf_test.FwdTest", 
        "----------------------------------------------------------------------", 
        "Traceback (most recent call last):", 
        "  File \"ptftests/vrf_test.py\", line 101, in runTest", 
        "    self.check_fwd_entries()", 
        "  File \"ptftests/vrf_test.py\", line 90, in check_fwd_entries", 
        "    self.check_ip_range(ip_range, next_hop, ipv4)", 
        "  File \"ptftests/fib_test.py\", line 204, in check_ip_range", 
        "    self.check_ip_route(src_port, dst_ip, exp_ports, ipv4)", 
        "  File \"ptftests/fib_test.py\", line 237, in check_ip_route", 
        "    res = self.check_ipv4_route(src_port, dst_ip_addr, dst_port_list)", 
        "  File \"ptftests/fib_test.py\", line 267, in check_ipv4_route", 
        "    router_mac = self.ptf_test_port_map[str(src_port)]['target_dest_mac']", 
        "KeyError: 'target_dest_mac'", 
        "", 
        "----------------------------------------------------------------------", 
        "Ran 1 test in 0.007s", 
        "", 
        "FAILED (errors=1)"
    ], 
    "stdout": "", 
    "stdout_lines": []
}

**Describe the results you expected:**
Test is passed

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by oleksandrKovtunenko** [comment]
i will try to fix it
