### ISSUE TITLE
ASYNC_PFC: test fail due to 'SAI_SCHEDULER_ATTR_SCHEDULING_ALGORITHM' attribute error

### ISSUE THREAD

**Issue by sudhavenkat** [Azure/sonic-mgmt#862]
**Description**

**Steps to reproduce the issue:**
1.  Running pfc_asym.yml  playbook 
ansible-playbook test_sonic.yml -i inventory -l switch96 -e testbed_name=hk-t0 -e testbed_type=t0 -e ptf_host=<ptf_ip> -e testcase_name=pfc_asym -e ptf_portmap=ptf-portmap.ini

3.

**Describe the results you received:**

ERROR: pfc_asym.PfcAsymOffOnTxTest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "saitests/pfc_asym.py", line 106, in setUp
    sched_prof_id = sai_thrift_create_scheduler_profile(self.client, self.STOP_PORT_MAX_RATE)
  File "saitests/switch.py", line 547, in sai_thrift_create_scheduler_profile
    attribute = sai_thrift_attribute_t(id=SAI_SCHEDULER_ATTR_SCHEDULING_ALGORITHM ,
NameError: global name 'SAI_SCHEDULER_ATTR_SCHEDULING_ALGORITHM' is not defined

----------------------------------------------------------------------
Ran 1 test in 11.264s

FAILED (errors=1)

******************************************
ATTENTION: SOME TESTS DID NOT PASS!!!

The following tests errored:
PfcAsymOffOnTxTest

******************************************

**Describe the results you expected:**

Shouldn't hit into any sai attribute issue. 

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```
show version
SONiC Software Version: SONiC.cisco-master.45-7f19521
Distribution: Debian 9.8
Kernel: 4.9.0-8-2-amd64
Build commit: 7f19521
Build date: Fri Apr  5 03:35:25 UTC 2019
Built by: saiadmin@insbu-saidev2

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by wendani** [comment]
Does your ptf docker have the latest SAI header in python-saithrift?

**Comment by rameshsanth** [comment]
Hi Wendani
The attribute SAI_SCHEDULER_ATTR_SCHEDULING_ALGORITHM doesn't exist in the SAI anymore.
it was there in 0.9.4 version and was  removed in 0.9.5.

At Cisco, we're working on the current SAI version used in SAIREDIS component of sonic, which is https://github.com/opencomputeproject/SAI/tree/1d42f1218ad537e37fac84aadb7f6232472bdd58

**Comment by lguohan** [comment]
@liat-grozovik , can you check this issue?
